/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

/**
 *
 * @author moisemb
 */
public class Acceuil extends javax.swing.JPanel {

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/careasy.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 420, 280));

        jLabel2.setFont(new java.awt.Font("Bradley Hand", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACCEUILL");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 210, 60));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenue dans la page Acceuil de carEasy   ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 550, 60));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nous sommes ravis de vous présenter notre plateforme de location de voitures");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 780, 30));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" développe en utilisant le langage Java, qui est un langage de programmation de haut niveau orienté objet.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 790, 30));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Nous sommes ravis de vous présenter notre plateforme de location de voitures rapide ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 830, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("et facile à utiliser, qui répondra à tous vos besoins de mobilité.Nous nous engageons a");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 830, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("à fournir un service de location de voitures fiable et efficace en toute Disponibilite.");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 830, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 850));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
