/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pack2.classeconnexion;
import pack2.pageconnexion;

/**
 *
 * @author moisemb
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
      
    }
    
    public String getlogin(){
        return champLogin.getText();
        
    }
    
    public String getpassword(){
        return champPassword.getText();
        
    }
    
    public void setpassword(){
         champPassword.setText("");
        
    }
    public void setlogin(){
         champLogin.setText("");
        
    }
    
    
    public void Actionconnexion(ActionListener evt){
        boutonconnect.addActionListener(evt);
    }
    
    public void  Login(){
      champLogin.grabFocus();
    }
    public void  addEventRegister(ActionListener evt){
            
    Inscription.addActionListener(evt);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boutonconnect = new javax.swing.JButton();
        champLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        champPassword = new javax.swing.JPasswordField();
        Inscription = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        boutonconnect.setText("Connect");
        boutonconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonconnectActionPerformed(evt);
            }
        });
        add(boutonconnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 200, 50));

        champLogin.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(champLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 320, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/login (1) 20.36.07.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 250, 190));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pas de compte  ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 700, -1, 30));

        champPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        champPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champPasswordActionPerformed(evt);
            }
        });
        add(champPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 320, 40));

        Inscription.setForeground(new java.awt.Color(255, 0, 51));
        Inscription.setText("S'inscrire");
        add(Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 700, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void boutonconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonconnectActionPerformed
        
       
        
    }//GEN-LAST:event_boutonconnectActionPerformed

    private void champPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inscription;
    private javax.swing.JButton boutonconnect;
    private javax.swing.JTextField champLogin;
    private javax.swing.JPasswordField champPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
