/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import static com.mysql.cj.util.SaslPrep.prepare;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import pack2.classeconnexion;

/**
 *
 * @author moisemb
 */
public class panelClientAjout extends javax.swing.JPanel {

    /**
     * Creates new form panelClientAjout
     */
    PreparedStatement prepare ;
    ResultSet rst;
    
    public panelClientAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sexe = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        validerAjout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        champNom = new javax.swing.JTextField();
        champPrenom = new javax.swing.JTextField();
        champAdresse = new javax.swing.JTextField();
        champTelephone = new javax.swing.JTextField();
        champCin = new javax.swing.JTextField();
        champEmail = new javax.swing.JTextField();
        sexeh = new javax.swing.JRadioButton();
        sexef = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AJOUT CLIENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 360, 70));

        validerAjout.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        validerAjout.setText("Valider");
        validerAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutActionPerformed(evt);
            }
        });
        add(validerAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 670, 180, 50));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOM");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 74, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRENOM");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADRESSE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEPHONE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 140, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CIN");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 90, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 120, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("sexe");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 120, 50));

        champNom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        champNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champNomActionPerformed(evt);
            }
        });
        add(champNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 300, 30));

        champPrenom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(champPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 300, 30));

        champAdresse.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(champAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 300, 30));

        champTelephone.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(champTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 300, 30));

        champCin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        champCin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champCinActionPerformed(evt);
            }
        });
        add(champCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 300, 30));

        champEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        champEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champEmailActionPerformed(evt);
            }
        });
        add(champEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 300, 30));

        sexe.add(sexeh);
        sexeh.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        sexeh.setForeground(new java.awt.Color(255, 255, 255));
        sexeh.setText("Homme");
        add(sexeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, -1));

        sexe.add(sexef);
        sexef.setForeground(new java.awt.Color(255, 255, 255));
        sexef.setText("Femme");
        add(sexef, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 850, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void champEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champEmailActionPerformed

    private void champCinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champCinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champCinActionPerformed

    private void champNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champNomActionPerformed

    private void validerAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutActionPerformed
        
        
           try {
    if(champNom.getText().isEmpty() || champPrenom.getText().isEmpty() || champEmail.getText().isEmpty() || champTelephone.getText().isEmpty() || champCin.getText().isEmpty() || champAdresse.getText().isEmpty() ){
        JOptionPane.showMessageDialog(this, "veuillez remplir tous les champs !");
    }else{
        classeconnexion conn= new classeconnexion(); //connexion a la base de donnees 
        prepare=conn.conn.prepareStatement("insert into Client(prenom,nom,email,telephone,CIN,adresse,sexe) values(?,?,?,?,?,?,?)" );
        prepare.setString(1,champPrenom.getText());
        prepare.setString(2,champNom.getText());
        prepare.setString(3,champEmail.getText());
        prepare.setString(4,champTelephone.getText());
        prepare.setString(5,champCin.getText());
        prepare.setString(6,champAdresse.getText());
        String sexe="";
        if(sexeh.isSelected()){
            sexe= "homme";
        }else if(sexef.isSelected()){
            sexe= "femme";
        }
        prepare.setString(7,sexe);
        int result = prepare.executeUpdate(); // execute la requête et retourne le nombre de lignes affectées
        if(result > 0){
            JOptionPane.showMessageDialog(null, "Ajout réussi");
            champPrenom.setText("");
            champNom.setText("");
            champEmail.setText("");
            champTelephone.setText("");
            champCin.setText("");
            champAdresse.setText("");
            
        }
    }
} catch (Exception e) {
//    e.printStackTrace(); 
 JOptionPane.showMessageDialog(null, "Erreur veuillez verifier tout les champs");  
}

    }//GEN-LAST:event_validerAjoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField champAdresse;
    private javax.swing.JTextField champCin;
    private javax.swing.JTextField champEmail;
    private javax.swing.JTextField champNom;
    private javax.swing.JTextField champPrenom;
    private javax.swing.JTextField champTelephone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup sexe;
    private javax.swing.JRadioButton sexef;
    private javax.swing.JRadioButton sexeh;
    private javax.swing.JButton validerAjout;
    // End of variables declaration//GEN-END:variables
}
