/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Client;
import classe.Reservation;
import classe.Voiture;
import java.sql.Date;
import java.util.Calendar;
import static com.mysql.cj.util.SaslPrep.prepare;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import pack2.classeconnexion;

/**
 *
 * @author moisemb
 */
public class panelReservationRecherche extends javax.swing.JPanel {

    /**
     * Creates new form panelClientAjout
     */
   
    
    public panelReservationRecherche() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sexe = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        validerAjout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        immatriculation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        marque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        modele = new javax.swing.JTextField();
        paiement = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jours = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        debut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recherche Reservation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 540, 70));

        validerAjout.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        validerAjout.setText("Valider");
        validerAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutActionPerformed(evt);
            }
        });
        add(validerAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 120, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date debut");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Fin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 140, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CIN Client");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prenom Client");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 150, 50));

        cin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 260, 30));

        prenom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 200, 30));

        immatriculation.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(immatriculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Immatriculation Voiture");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 50));

        marque.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 200, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prix total location");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, 180, 30));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("modele");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 80, 50));

        prix.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 220, 30));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nom CLient");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 120, 50));

        nom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 200, 30));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("marque");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 50));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CFA");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 660, 50, 30));

        modele.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 200, 30));

        paiement.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(paiement, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 140, 30));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Paiement");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 150, 30));

        jours.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(jours, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 140, 30));

        fin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 140, 30));

        debut.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 140, 30));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nombre jours");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -3, 850, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void validerAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutActionPerformed
        try{
        
        
        if(cin.getText().isEmpty() ||immatriculation.getText().isBlank()  ){
        JOptionPane.showMessageDialog(this, "veuillez remplir les  2 champs !");
    }else{

        Voiture v=new Voiture();
        Client cl=new Client();

        v.setMatriculation(immatriculation.getText());
        cl.setCin(Integer.parseInt(cin.getText()));
        
        
        cl.clientexiste();
        v.Voitureexiste();
        
        Reservation rv=new Reservation();
        
        rv.RechercheReservation(immatriculation.getText(),Integer.parseInt(cin.getText()));
        
        
          
            
            
            if(rv.getDateDebut()==null){return;}
          
    
  
    
    
    
              nom.setText(cl.getNom());
            prenom.setText(cl.getPrenom());
            marque.setText(v.getMarque());
            modele.setText(v.getModele());
            debut.setText(String.valueOf(rv.getDateDebut()));
            fin.setText(String.valueOf(rv.getDateFin()));
           
            prix.setText(String.valueOf(rv.getPrixLocation()));
       String pt;
               if(rv.isEtatReservation()){
               pt="valider";
                   
               }else{pt="invalide";}
        
               paiement.setText(pt);
               jours.setText(String.valueOf(rv.getDelta()));
               
        
            
        }
        }catch(Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_validerAjoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin;
    private javax.swing.JTextField debut;
    private javax.swing.JTextField fin;
    private javax.swing.JTextField immatriculation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jours;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField modele;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField paiement;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prix;
    private javax.swing.ButtonGroup sexe;
    private javax.swing.JButton validerAjout;
    // End of variables declaration//GEN-END:variables
}
