/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Enumcarburant;
import classe.Voiture;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author moisemb
 */
public class panelVoitureAjout extends javax.swing.JPanel {

    /**
     * Creates new form panelVoitureAjout
     */
    public panelVoitureAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        annee = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        immatriculation = new javax.swing.JTextField();
        kilometrage = new javax.swing.JTextField();
        marque = new javax.swing.JTextField();
        modele = new javax.swing.JTextField();
        choixImage = new javax.swing.JButton();
        valider = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        place = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        carburant = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajout Voiture");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 280, 50));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marque");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modele");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Annee");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kilometrage");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, 40));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Immatriculation");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 40));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("nombre place");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, 30));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prix location");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Image");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        annee.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(annee, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 260, 30));
        add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 180, 30));

        immatriculation.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(immatriculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 260, 30));

        kilometrage.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(kilometrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 260, 30));

        marque.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 260, 30));

        modele.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 260, 30));

        choixImage.setText("Choisir Image");
        choixImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixImageActionPerformed(evt);
            }
        });
        add(choixImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 120, 30));

        valider.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        add(valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, 110, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CFA");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, 30));

        place.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        place.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "5", "7" }));
        add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 50, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 3, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Carburant");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, 30));

        carburant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essence", "Super", "Diesel" }));
        add(carburant, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        jLabel12.setText("jLabel12");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed

        
        String c =place.getSelectedItem().toString();
        int m=Integer.parseInt(c);
        
        
                
        if(modele.getText().isBlank() || marque.getText().isBlank() || annee.getText().isBlank() || kilometrage.getText().isBlank() || immatriculation.getText().isBlank()  || prix.getText().isBlank() )  {
        
            JOptionPane.showMessageDialog(null, "Veuillez renseigner tout les champs");
            return;
        } else{      
        
        Voiture v=new Voiture(immatriculation.getText(),modele.getText(),marque.getText(),Integer.valueOf(annee.getText()),m,Integer.valueOf(kilometrage.getText()),true,Enumcarburant.valueOf(carburant.getSelectedItem().toString().toUpperCase()),Integer.valueOf(prix.getText()));
        
        v.ajouterVoiture();
        }
    }//GEN-LAST:event_validerActionPerformed

   

    private void choixImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixImageActionPerformed
       
        try {
    JFileChooser choix = new JFileChooser();
    FileNameExtensionFilter filtre = new FileNameExtensionFilter("image png", "png");
    choix.setFileFilter(filtre);
    choix.showOpenDialog(this);

    File f = choix.getSelectedFile();


    File destination = new File("photoVoiture/" + immatriculation.getText() + ".png");
        
    Files.copy(f.toPath(), destination.toPath(),StandardCopyOption.REPLACE_EXISTING);
   
    
    

} catch (IOException ex) {
     JOptionPane.showMessageDialog(null, "Erreur lors de la recuperation du fichier");
}


        
    }//GEN-LAST:event_choixImageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annee;
    private javax.swing.JComboBox<String> carburant;
    private javax.swing.JButton choixImage;
    private javax.swing.JTextField immatriculation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kilometrage;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField modele;
    private javax.swing.JComboBox<String> place;
    private javax.swing.JTextField prix;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
