/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import classe.Client;
import classe.Reservation;
import classe.Voiture;
import java.sql.Date;
import java.util.Calendar;
import static com.mysql.cj.util.SaslPrep.prepare;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import pack2.classeconnexion;

/**
 *
 * @author moisemb
 */
public class panelReservationAjout extends javax.swing.JPanel {

    /**
     * Creates new form panelClientAjout
     */
    PreparedStatement prepare ;
    ResultSet rst;
    
    public panelReservationAjout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sexe = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        validerAjout = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        fin = new com.toedter.calendar.JDateChooser();
        debut = new com.toedter.calendar.JDateChooser();
        immatriculation = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        marque = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        modele = new javax.swing.JTextField();
        jours = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        confirmer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AJOUT Reservation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 500, 70));

        validerAjout.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        validerAjout.setText("Valider");
        validerAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutActionPerformed(evt);
            }
        });
        add(validerAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 120, 30));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date debut");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date Fin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 30));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CIN Client");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Prenom Client");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 150, 50));

        cin.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 260, 30));

        prenom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 200, 30));

        fin.setDateFormatString("dd-MM-yyyy");
        add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 260, 30));

        debut.setDateFormatString("dd-MM-yyyy");
        debut.setMinSelectableDate(new java.util.Date(-62135765933000L));
        add(debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 260, 30));

        immatriculation.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(immatriculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 30));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Immatriculation Voiture");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 50));

        marque.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(marque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 200, 30));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prix total location");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 180, 30));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("modele");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 50));

        prix.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(prix, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 190, 30));

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nom CLient");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 120, 50));

        nom.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 200, 30));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("marque");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 80, 50));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CFA");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 50, 30));

        modele.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(modele, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 200, 30));

        jours.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        add(jours, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 120, 30));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 3, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre jours");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 150, 30));

        confirmer.setBackground(new java.awt.Color(0, 153, 0));
        confirmer.setForeground(new java.awt.Color(255, 255, 255));
        confirmer.setText("Confirmer");
        confirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerActionPerformed(evt);
            }
        });
        add(confirmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -3, 860, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void validerAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutActionPerformed
        try{
        
        
        if(cin.getText().isEmpty() ||immatriculation.getText().isBlank() || debut.getDate().toString().isEmpty() || fin.getDate().toString().isEmpty()  ){
        JOptionPane.showMessageDialog(this, "veuillez remplir tous les champs !");
    }else{

        Voiture v=new Voiture();
        Client cl=new Client();
        
        v.setMatriculation(immatriculation.getText());
        cl.setCin(Integer.parseInt(cin.getText()));
        if(v.Voitureexiste() && cl.clientexiste()  ){
        
          
            
            
             Date debut1=new Date(debut.getDate().getTime());
              Date fin1=new Date(fin.getDate().getTime());
            
                LocalDate db = debut1.toLocalDate();
                LocalDate fn = fin1.toLocalDate();
                int pr;
    
  int duree = (int)(ChronoUnit.DAYS.between(db, fn));
    
    if (duree < 0) {
        JOptionPane.showMessageDialog(null, "Erreur : la date de fin ne peut pas être antérieure à la date de début.");
        return;
    } else if (duree == 0) {
        pr = v.getPrix_location();
    } else {
        pr = v.getPrix_location() * duree;
    }
    
              nom.setText(cl.getNom());
            prenom.setText(cl.getPrenom());
            marque.setText(v.getMarque());
            modele.setText(v.getModele());           //on affiche quelque informations sur les voitures 
            jours.setText(String.valueOf(duree));
            prix.setText(String.valueOf(pr));
            

        }else{
        if(!v.Voitureexiste())JOptionPane.showMessageDialog(null, "Le numéro d'immatriculation renseigné pour la voiture n'existe pas.");
        if(!cl.clientexiste())JOptionPane.showMessageDialog(null, "Le CIN renseigné pour le client n'existe pas.");
            }

        
        
        
            
        }
        }catch(Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_validerAjoutActionPerformed

    private void confirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerActionPerformed
        
        
    try {
    if(cin.getText().isEmpty() || prenom.getText().isEmpty() || debut.getDate().toString().isEmpty() || fin.getDate().toString().isEmpty() || modele.getText().isBlank()  || marque.getText().isBlank() || nom.getText().isBlank() || prenom.getText().isBlank() ){
        JOptionPane.showMessageDialog(this, "Erreur ! Verifier si la validation c'est bien passer");
    }else{
        
   
        Reservation rv=new Reservation();
        
                
                
                Date debut1=new Date(debut.getDate().getTime());
                Date fin1=new Date(fin.getDate().getTime());
        
        
        

        
        rv.setDateDebut(debut1);
        
        rv.setDateFin(fin1);
        
        rv.ajouterReservation(immatriculation.getText(), Integer.valueOf(cin.getText()));
        
        
        
                   prenom.setText("");
            nom.setText("");
            modele.setText("");
            jours.setText("");           //On vide ensuite les champs
            prix.setText("");
            cin.setText("");
            immatriculation.setText("");
            marque.setText("");
       
    }
} catch (Exception e) {

 e.printStackTrace();
}

    }//GEN-LAST:event_confirmerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin;
    private javax.swing.JButton confirmer;
    private com.toedter.calendar.JDateChooser debut;
    private com.toedter.calendar.JDateChooser fin;
    private javax.swing.JTextField immatriculation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jours;
    private javax.swing.JTextField marque;
    private javax.swing.JTextField modele;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prix;
    private javax.swing.ButtonGroup sexe;
    private javax.swing.JButton validerAjout;
    // End of variables declaration//GEN-END:variables
}
