/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.event.ActionListener;

/**
 *
 * @author moisemb
 */
public class register extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
    }
    
    public void Register(){
        nom.grabFocus();
        
    }
    
      public String getnom(){
        return nom.getText();
    }
       public String getprenom(){
        return prenom.getText();
    }

         public String getlogin(){
        return login.getText();
    }

     public String getpassword1(){
        return password1.getText();
    }

     public String getpassword2(){
        return password2.getText();
    }
     
             public void setnom(){
         nom.setText("");
        }
             
       public void setprenom(){
         prenom.setText("");
        }

         public void setlogin(){
         login.setText("");
        }

        public void setpassword1(){
         password1.setText("");
        }

        public void setpassword2(){
         password2.setText("");
        }

   
    
    
    
        public void  addEventconnect(ActionListener evt){
            
    connecter.addActionListener(evt);
    }
        
        public void  Actioninscription(ActionListener evt){
            
        inscrire.addActionListener(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inscrire = new javax.swing.JButton();
        login = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        connecter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        inscrire.setText("REGISTER");
        inscrire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(inscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 200, 50));

        login.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 320, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vous avez un compte");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, -1, 30));

        nom.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 320, 40));

        password1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 320, 40));

        password2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 320, 40));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 3, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 3, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("confirm");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 3, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prenom");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        prenom.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 320, 40));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 3, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("REGISTER");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 300, 50));

        connecter.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        connecter.setForeground(new java.awt.Color(255, 0, 0));
        connecter.setText("Se Connecter");
        connecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 710, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/background.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -3, 730, 860));
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connecter;
    private javax.swing.JButton inscrire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
